info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

server:
  port: 8080
  servlet:
    contextPath: /api
  shutdown: graceful

spring:
  cloud:
    schemaRegistryClient:
      endpoint: http://localhost:8990/
      cached: true
    stream:
      bindings:
        output:
          contentType: application/*+avro
#    schema:
#      avro:
#        dynamicSchemaGenerationEnabled: true
  redis:
    host: localhost
    timeout: 15s
    port: 6379

camel:
  component:
    rabbitmq:
      hostname: localhost
      port-number: 5672
      username: guest
      password: guest
      vhost: /
      skip-exchange-declare: true
      auto-delete: false
      guaranteed-deliveries: true
      automatic-recovery-enabled: true
      publisher-acknowledgements-timeout: 10000
      requested-heartbeat: 20
      channel-rpc-timeout: 30000